### ISSUE TITLE
Linux: /usr/bin/env: node --harmony: No such file or directory

### ISSUE THREAD

**Issue by jnv** [njpatel/grpcc#10]
Unfortunately `env` in Linux doesn't support arguments, so executing `grpcc` fails immediately. Omitting 

See discussion in SpencerCDixon/redux-cli#42 on possible solutions. grpcc seems to work well with the stable Node even without the `--harmony` flag.

**Comment by vlad-doru** [comment]
I fixed this by just doing `sudo vim /usr/bin/grpcc` and then changed the shebang to `#!/usr/bin/node --harmony`

**Comment by jnv** [comment]
@vlad-doru Well, unfortunately that doesn't really help in case you have Node in another path, say installed through nvm.

**Comment by njpatel** [comment]
Should be fixed with latest release. Please reopen if you have the issue again, sorry for the delay.
