### ISSUE TITLE
Request for more examples

### ISSUE THREAD

**Issue by nscsekhar** [njpatel/grpcc#12]
Firstly thanks for putting this tool out.

I am having issues sending GRPC requests where the input is a message with more than one fields. Can you please provide examples for such cases ares.

MyCli@unix:/tmp/my_socket> client.createRequest({name: "Hello", input: 2, output: 4}, printReply)
EventEmitter {}
MyCli@unix:/tmp/my_socket> Error:  { [Error] code: 12, metadata: Metadata { _internal_repr: {} } }

I tried other json style combinations and I keep getting more basic errors, hence the request..

Thanks!!

**Comment by Crevil** [comment]
It should be as you wrote. It is nothing but plain javascript objects.

```javascript
client.createRequest({name: "Hello", input: 2, output: 4}, printReply)
```
Can you share the proto file for a better context?

**Comment by natemurthy** [comment]
I'm having a similar issue. I have a proto file that looks like this:
```proto
syntax="proto3";

package solver;

service Solver {
  rpc SolveQuadratic(SolverRequest) returns (SolverResponse) {}
}

message SolverRequest {
  float a = 1;
  float b = 2;
  float c = 3;
}

message SolverResponse {
  float x = 1;
  float y = 2;
}
```
And I get this error when I make the following request:
```js
Solver@127.0.0.1:50051> client.solveQuadratic( {a:1, b:4, c:1}, pr)
EventEmitter {}
Solver@127.0.0.1:50051> Error:  { Error: Connect Failed
    at /usr/local/lib/node_modules/grpcc/node_modules/grpc/src/node/src/client.js:554:15 code: 14, metadata: Metadata { _internal_repr: {} } }
```

**Comment by njpatel** [comment]
Sorry for the delay on this, I just pushed a huge update and also added a bunch of examples (client and server):

https://github.com/njpatel/grpcc#examples (make sure to upgrade your grpcc too!)
