### ISSUE TITLE
Error when importing google/protobuf/*

### ISSUE THREAD

**Issue by nvartolomei** [njpatel/grpcc#13]
Why it can't find `google/protobuf` package?

```proto
syntax = "proto3";
package eventstream;

import "google/protobuf/struct.proto";
```

```
eventstream/google/protobuf/struct.proto' in './vendor/proto/eventstream/rpc.proto': file not found
```

**Comment by rogchap** [comment]
This is still an issue. Using version 0.0.5
Ps. `--version` is hardcoded to 0.0.1

**Comment by njpatel** [comment]
Sorry - I've been lost in my startup past few months, I'll take a look at this and other bugs over the weekend!

**Comment by guiocavalcanti** [comment]
hey, any news here? :D
