### ISSUE TITLE
Definitions are not found if package path is deeper than one level

### ISSUE THREAD

**Issue by SamiHiltunen** [njpatel/grpcc#16]
Hey,

Just had a confusing moment with the tool. Basically, the tool seems to fail when loading packages from deeper path levels than the first one. Something like `package example;` works and the tool correctly finds the definitions. If I have something like `package com.example.v1;`, the tool will not find the definitions and exits silently with no error message. 

The error happens [`choices: Object.keys(parsed)`](https://github.com/njpatel/grpcc/blob/master/lib/index.js#L26) as it is currently not traversing the hierarchy stored in [`let parsed = grpc.load(file);`](https://github.com/njpatel/grpcc/blob/master/lib/index.js#L16) but instead just lists the top level packages

**Comment by angelbeltran** [comment]
I wrote what I believe fixes this issue in pull request #17 . If you'll like to try using it, let us know if it works for you.

**Comment by SamiHiltunen** [comment]
Awesome, thanks! I will give it a spin once I am back in the office on Wednesday.
