### ISSUE TITLE
Does not handle dot-delimited packages

### ISSUE THREAD

**Issue by rocketraman** [njpatel/grpcc#19]
When using dot-delimited packages (as is usual in the java world) e.g. "com.foo.package", grpcc only offers the first path component as an option:

```
grpcc --proto My.proto --directory path/to/proto/ --address localhost:8091 -i
? What package you want to use? com
(node:17275) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Unable to locate service undefined in My.proto
```

**Comment by ndandanov** [comment]
Hello,

Unfortunately, after uninstalling grpcc with `npm uninstall -g grpcc` and installing it from your repository with `npm install -g https://github.com/rodrigosetti/grpcc.git`, I still get the error:
`(node:7486) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Unable to locate service undefined in protos/MonitoringUnitService.V1.proto`

The same proto file works correctly with https://github.com/grpc/grpc/blob/master/doc/command_line_tool.md.
