### ISSUE TITLE
Cannot find module '/usr/local/lib/node_modules/grpcc/node_modules/grpc/src/node/extension_binary/grpc_node.node'

### ISSUE THREAD

**Issue by scampiuk** [njpatel/grpcc#21]
Hi,
```
$ grpcc --proto ./some.proto --address someaddresss
module.js:328
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/grpcc/node_modules/grpc/src/node/extension_binary/grpc_node.node'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/grpcc/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

```

**Comment by njpatel** [comment]
I just pushed a new release (0.0.7) with a bunch of fixes, could you please see if this is still an issue?

**Comment by har07** [comment]
@njpatel How to install the latest, 0.0.7, version? Installing from `npm` gave version 0.0.6 for me, and then the above mentioned error occurred. Thanks in advance

**Comment by njpatel** [comment]
@har07 sorry, i meant 0.0.6 - can you share a proto file that causes the error? I can't reproduce it locally.

**Comment by har07** [comment]
@njpatel I've just reinstall grpcc using `npm`, and I can confirm it works! (not sure what was wrong the last time I tried). Tested, and worked, in both Windows 10 and Ubuntu 16.10.

**Comment by jeremyjjbrown** [comment]
Same here:

```
 $ grpcc --proto ~/Dev/src/github.com/skizzehq/skizze/src/datamodel/protobuf/skizze.proto localhost:3596 -i
module.js:328
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/grpcc/node_modules/grpc/src/node/extension_binary/grpc_node.node'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/grpcc/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)


 $ ls /usr/local/lib/node_modules/grpcc/node_modules/grpc/src/node
ext  index.js  README.md  src
```
looks like maybe the wrong version of grpc installed.

**Comment by mribeiro** [comment]
Having the same issue. @jeremyjjbrown , did you find a solution?

**Comment by helloandy11** [comment]
same issue even at grpcc -V and grpcc -H

  @mribeiro @jeremyjjbrown @njpatel - how was this solved?

on ubuntu 16.04.2 LTS - did uninstall - reinstall of NPM, Node, NodeJs but no luck.
grpcc v0.0.6
node v4.2.6

**Comment by helloandy11** [comment]
ok. figured out what the problem is, the grpc inside the grpcc does not have all the required code. so did the following:
installed grpc using "npm install -g grpc", this will install grpc in a folder parallel to grpcc
next from the folder that has both grpc and grpcc "sudo cp -r grpc grpcc/node_modules" to copy over the new global grpc to the local one. 
this fixed it for me. 
good luck

**Comment by njpatel** [comment]
I'll update grpcc to the latest grpc sometime today

**Comment by njpatel** [comment]
I pushed up `v0.0.8` which forces a minimum `grpc` version of `1.4.1`. Obviously something changed between minor versions upstream but it hasn't been a major bump. Also this should stop npm from deciding not to update the deps of `grpcc` when you install/update. Re-open if there are any issues. Thanks!

**Comment by danielsnider** [comment]
Got this issue on gcpcc 1.0.0. Any tips?

Installed for the first time today with `sudo npm install -g grpcc`.

npm list
```
dan@ubuntu:~/grpc/grpc/examples/node/dynamic_codegen$ npm -g list | head
/usr/local/lib
├─┬ grpcc@1.0.0
│ ├── colors@1.1.2
│ ├── commander@2.11.0
│ ├─┬ eval@0.1.2
│ │ └── require-like@0.1.2
│ ├─┬ grpc@1.6.6
│ │ ├── arguejs@0.2.3
│ │ ├── lodash@4.17.4
│ │ ├── nan@2.7.0
```

Error:
```
dan@ubuntu:~/grpc/grpc/examples/node/dynamic_codegen$ grpcc --proto /../../protos/helloworld.proto --address 127.0.0.1:50051                                            
module.js:328
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/grpcc/node_modules/grpc/src/node/extension_binary/node-v46-linux-x64/grpc_node.node'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/grpcc/node_modules/grpc/src/node/src/grpc_extension.js:30:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
```

**Comment by njpatel** [comment]
`/../../protos/helloworld.proto`, are you missing a `.` in front of that (or was a copy-paste error?)

**Comment by danielsnider** [comment]
Fixed the typo but the error is still happening. 
```
dan@ubuntu:~/grpc/grpc/examples/node/dynamic_codegen$ file ../../protos/helloworld.proto
../../protos/helloworld.proto: Perl5 module source, ASCII text
dan@ubuntu:~/grpc/grpc/examples/node/dynamic_codegen$ grpcc --proto ../../protos/helloworld.proto --address 127.0.0.1:50051
module.js:328
    throw err;
    ^
```
Can I help you in any way possible?

**Comment by njpatel** [comment]
Sounds like you're hitting this? https://github.com/grpc/grpc/issues/6435#issuecomment-217039715

**Comment by njpatel** [comment]
@danielsnider someone else came across this and said that they had luck installing it locally (to user home dir) rather than with `npm install -g` - something to do with the gprc modules not being able to compile due to permissions. Might be worth a try.

**Comment by danielsnider** [comment]
I really appreciate your bonus suggestion. I haven't gotten the time to fix
my problem but I still have to :-). Thanks!

On Thu, Nov 2, 2017 at 2:29 PM, Neil Jagdish Patel <notifications@github.com

**Comment by kirillgroshkov** [comment]
I have the same issue!

**Comment by njpatel** [comment]
@kirillgroshkov did you try https://github.com/njpatel/grpcc/issues/21#issuecomment-341516677 ?

**Comment by ivanivkovic** [comment]
> ok. figured out what the problem is, the grpc inside the grpcc does not have all the required code. so did the following:
> installed grpc using "npm install -g grpc", this will install grpc in a folder parallel to grpcc
> next from the folder that has both grpc and grpcc "sudo cp -r grpc grpcc/node_modules" to copy over the new global grpc to the local one.
> this fixed it for me.
> good luck

I love you. This worked.
