### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by har07** [njpatel/grpcc#22]
I tried to run `grpcc` using simple .proto file : 

![image](https://cloud.githubusercontent.com/assets/11190794/25607365/5eac1c76-2f40-11e7-9849-b7b2540f296d.png)

But after hitting Enter the error message mentioned in the title appeared : 

![image](https://cloud.githubusercontent.com/assets/11190794/25607411/a25fdcf0-2f40-11e7-8338-060cf7926db8.png)

Even using [the .proto file](https://github.com/skizzehq/skizze/blob/master/src/datamodel/protobuf/skizze.proto) mentioned in `grpcc` example yielded the same error for me.

What can possibly be the cause and how to fix it? Anybody else, probably in a different environment (OS, version of `npm` and `node`), experiencing this error?

I can reproduce the error on Windows 10, using the following version of `node` & `npm` : 

```
λ node -v
v6.10.2
λ npm -v
3.10.10
```
as well as on Ubuntu 16.10, using higher version of `node` & `npm` : 

```
$ node -v
v7.9.0
$ npm -v
4.2.0
```

**Comment by bobbytables** [comment]
I'm seeing this as well.
