### ISSUE TITLE
incorrectly reading top-level enums as packages

### ISSUE THREAD

**Issue by ehudc** [njpatel/grpcc#31]
If enum is outside a message (top-level), grpcc picks up on the enum and considers it a package name, rendering the tool unusable.

e.g.

````
package grpcctest;

enum EventType {
  TEST = 0;
  TEST_AGAIN = 1;
}
````

````
What package you want to use? (Use arrow keys)
❯ grpcctest.EventType.TEST
  grpcctest.EventType.TEST_AGAIN
````

Expected: 
````
What package you want to use? (Use arrow keys)
❯ grpcctest
````

**Comment by ehudc** [comment]
I see this was just closed, but the [commit](https://github.com/njpatel/grpcc/commit/baa628f22ecd6cc4b6c45fdd9232f0b087e3c93f) seems to be failing on [circle](https://circleci.com/gh/njpatel/grpcc/33?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

I'd add these for test cases in test.proto, haven't gotten around to testing myself yet.
````
enum EventType {
  TEST = 0;
  TEST_AGAIN = 1;
}

message SayThing {
  enum NumberThing {
    THING_ONE = 0;
    THING_TWO = 1;
  }
}
````

**Comment by njpatel** [comment]
Yeah, it worked locally but CircleCI is not loading for me - I get to the main build page but the output won't load. I'm still working on grpcc, so will  keep a look out until it's working again.

**Comment by njpatel** [comment]
Ah, I see it now, I moved a few things around and the tests need updating. Shall do so tomorrow!

**Comment by netdragonboberb** [comment]
I saw this as well. Another example (names changed and simplified.

message XRequest {
  MyEnum val = 1;
  string somethingElse = 2;
}
message YRequest {
  MyEnum val = 1;
}

enum MyEnum{
  EntryOne = 0;
  EntryTwo = 1;
}

**Comment by joeblubaugh** [comment]
+1 I also just ran into this bug. It's a shame, since it prevents me from using the program at all.

**Comment by bogatuadrian** [comment]
+1

**Comment by MitchDart** [comment]
+1

**Comment by maurofran** [comment]
+1

**Comment by bgiegel** [comment]
+1 very

**Comment by njpatel** [comment]
Sorry for the delay on this, I've just published a big release of `grpcc`, so please upgrade and check it out. I can no-longer recreate the issue.

Also you may want to take at the new features https://github.com/njpatel/grpcc :)

**Comment by ehudc** [comment]
Thanks for the update!

**Comment by bgiegel** [comment]
Hi !

Ok it works now :)

Thank you !

Bastien Giegel

2017-10-23 20:56 GMT+02:00 ehud <notifications@github.com>:
