### ISSUE TITLE
Feature request: request header customization 

### ISSUE THREAD

**Issue by demongaorui** [njpatel/grpcc#35]
For test auth protected apis in server side, could  request header customization feature be added? Or, do we already have this function?  Didn't see docs about this feature.

**Comment by Disturbing** [comment]
Agreed -

Is it possible to send client headers and receive server headers?

**Comment by njpatel** [comment]
If you mean `metadata`, I've just pushed a new 1.0.0 release as well as added an example in `examples/unary.js`

https://github.com/njpatel/grpcc#examples

**Comment by rafaelalmeida** [comment]
@njpatel Not really - gRPC metadata goes in the HTTP/2 body, but some use cases use HTTP/2 _headers_ to route and/or authenticate stuff _before_ it even reaches gRPC code.
