### ISSUE TITLE
Streaming example needed

### ISSUE THREAD

**Issue by netdragonboberb** [njpatel/grpcc#40]
Please provide a streaming example through command line interactive mode. Something like the following:
 var call=client.getSomething({id_list=["1","2","3"]});call.on('data', function(feature){console.log(feature)});

**Comment by njpatel** [comment]
Check out the  [examples](https://github.com/njpatel/grpcc#examples) I've just added (don't forget to upgrade to latest `grpcc`!). Hope that helps!
