### ISSUE TITLE
Allow a .proto include path to be specified on the command line 

### ISSUE THREAD

**Issue by zackangelo** [njpatel/grpcc#5]
Often times, .proto files will depend on .proto file that aren't in the same directory (they may be on a system include path or pulled in as part of a dependency).  

Would it be possible to have a command line option that specifies a search path for included .protos (similar to `protoc`)?

**Comment by chakming** [comment]
i make a hacky one: https://github.com/chakming/grpcc
1. according to [discssion here](https://groups.google.com/forum/#!msg/grpc-io/dyW20qtTR3Q/FnCtYsVNcxgJ) 
grpc usage could be `grpc.load({root:'your/root', file: 'your/file'})` which help to load multiple files
2. if load multiple proto at the same time and those package names are different, we need to have a power to let people choose the package name. I've implemented it with `inquirer`

**Comment by chakming** [comment]
you could tried the version with the following:
1. `npm install -g git://github.com/chakming/grpcc.git#master` so to install a specific npm repo from github
2. run the command with one more directory (didn't make a default one = pwd yet) with protos under same directory: `grpcc --proto helloworld.proto --directory $(pwd) --addess 127.0.0.1:3466 --insecure`

**Comment by njpatel** [comment]
@chakming nice one! Would you want to do a PR to the main branch? Would love to have this part of a fix-up release I'd like to do by the weekend.

**Comment by chakming** [comment]
sure i'd love to, just updated to fix the ci tests too

**Comment by njpatel** [comment]
I pushed up `v0.0.3` to npm just now, with your work included. Thank you!
